### ISSUE TITLE
Message count

### ISSUE THREAD

**Issue by eush77** [kilianc/rtail#101]
I would like UI to display message count somewhere at the top.

It would be nice to be able to filter a log and see how many times a particular event happened.

Is this a feature rtail UI could have at some point?

**Comment by kilianc** [comment]
@eush77 thanks for contributing!

Do you mind explaining your use case?

**Comment by eush77** [comment]
I was just studying the logs of the program I'm working on and found a need
to gather some basic statistics on the messages the logs are composed of
(basically `sort |uniq -c`, to compare two messages with each other based
on the number of times they appear in the log), so I switched to the shell
and did just that.

However, since the messages are already in the DOM and in some model in JS
I guess it is easy to render the total number of messages (after filtering)
somewhere.

I'm currently using it locally, but I could imagine running the main
program on one host and rtail server on the other and facing the same need.

**Comment by kilianc** [comment]
It sounds a little bit specific to your use case to be honest. Considering that dynamic (regexp) filters with notifications, colors, stats, etc will be part of rtail soon this will be probably covered by that.

I will go ahead and close this but feel free to move forward the conversation if needed.

Thanks again @eush77 !
