### ISSUE TITLE
Override defaults

### ISSUE THREAD

**Issue by kevintraver** [kilianc/rtail#108]
It would be nice override defaults in a config file. Maybe something like `~/.rtail`

**Comment by kilianc** [comment]
Hey @kevintraver thanks for stopping by.

In particular are you referring to the server or the client ? I have thought about this in the past but people seem to be very opinionated about file naming, location, format etc...

I would more likely add a `--config-file` using the [config](https://github.com/lorenwest/node-config) module on npm which will give us OOTB support for `yml`, `json`, `hjson` [etc](https://github.com/lorenwest/node-config/wiki/Configuration-Files#file-formats)

I see no harm in having `--config-file` in both server and client.

Not sure yet what the behavior should be for mixed args+file options, I think args should always override the config file.

PR is welcome.

**Comment by kbariotis** [comment]
@kilianc the config module expects to find the configuration files inside the root of the project. But many people will install rtail globally. Having a ~/.rtail config file seems more appropriate.

**Comment by kevintraver** [comment]
Fixed in #113
