### ISSUE TITLE
define list of fonts on google fonts

### ISSUE THREAD

**Issue by kilianc** [kilianc/rtail#19]

**Comment by kilianc** [comment]
@lucaorio 

* Source Sans Pro
* Source Code Pro
* Roboto
* Inconsolata
* Open Sans

what you think?

**Comment by lucaorio** [comment]
I think they look great!

Based on this poll http://www.slant.co/topics/67/~what-are-the-best-programming-fonts I would add one of these too:

* Anonymous Pro
* Ubuntu Mono
* Droid Sans Mono

**Comment by kilianc** [comment]
:+1: let's take a look at these live before merging the PR
