### ISSUE TITLE
make backlog size configurable

### ISSUE THREAD

**Issue by rmchale** [kilianc/rtail#42]
I was using this for a java log and a stacktrace was longer than the buffer.  If I have the available RAM could there be an option to control the buffer size? 

In the mean time is there a place I can hack this in?

**Comment by kilianc** [comment]
can you please post the stack trace or any error log you have?

**Comment by rmchale** [comment]
Sure.  FWIW, I think we routinely set out logging buffers to between 1000 & 10K lines.

**Comment by kilianc** [comment]
ok so by `buffer` you mean backlog size? the amount of lines you can see in the webapp at the same time ?

**Comment by rmchale** [comment]
Yes, exactly.

**Comment by kilianc** [comment]
at the moment we have 100 lines as value, based on the purpose itself of rtail, I guess adding `--backlog-size` won't hurt but I need to patch the webapp also.

I'll mark this as feature request and make it happen by EOW.

Meanwhile git clone and search and replace for `100` it whould match 2 lines on both app and cli.
then `gulp app` and `npm link` and you're set.

Dev notes are not ready yet.

**Comment by rmchale** [comment]
Thanks!

**Comment by kilianc** [comment]
https://github.com/kilianc/rtail/blob/develop/cli/rtail-server.js#L101
https://github.com/kilianc/rtail/blob/develop/app/app.ejs#L18

**Comment by kilianc** [comment]
after putting some thought in it, I decided to not implement this functionality. I would like to understand what exactly is your use case and why you need it. The reason I am reluctant to allow big buffer sizes is that this thing runs in the browser and we have `BUFFER_SIZE` dom elements inside an ng-repeat.

Performances will drop drastically with too many elements.

The purpose of this is to have centralized realtime logs, not rolling out 10k log lines at once, I am open to change my mind if you have a solid use case for this. I'll be happy to reopen this.

**Comment by rmchale** [comment]
I am trying to look at log data.  My use case was that got a stacktrace and
it didn't even fit into 100 lines.  Meaning I couldn't even see the error I
needed to look at. Which is why I was using rtail in the first place.  I am
unable to use rtail to view the logs and forced to go back to using tail.

Ryan

------------------------------
<http://blog.mchaler.org>  <http://twitter.com/rmchale>
<http://www.facebook.com/ryan.mchale>

**Comment by rmchale** [comment]
This is the logging for ONE request in my app.  As you can see its well over 100 lines

2015-03-30 14:57:00,065 INFO  [][89f0ee6696] com.networkedinsights.rest.search.elasticsearch.SearchExecution$QueryLogger - Query for cluster esdev_aud_vert on indices [[media_2015_05, media_2015_07, media_2015_06, media_2015_08]]:{
  "size" : 0,
  "query" : {
    "query_string" : {
      "query" : "smartwatch,
      "default_field" : "all"
    }
  },
  "filter" : {
    "bool" : {
      "must" : [ {
        "term" : {
          "ni.language" : "en"
        }
      }, {
        "term" : {
          "dataview" : "7777"
        }
      }, {
        "range" : {
          "ni.authored_date" : {
            "from" : "2015-02-01T00:00:00",
            "to" : "2015-02-17T00:00:00",
            "include_lower" : true,
            "include_upper" : false
          }
        }
      } ]
    }
  },
  "facets" : {
    "posts_by_date" : {
      "date_histogram" : {
        "field" : "authored_date",
        "interval" : "day"
      },
      "facet_filter" : {
        "bool" : {
          "must" : [ {
            "term" : {
              "ni.language" : "en"
            }
          }, {
            "term" : {
              "dataview" : "7777"
            }
          }, {
            "range" : {
              "ni.authored_date" : {
                "from" : "2015-02-01T00:00:00",
                "to" : "2015-02-17T00:00:00",
                "include_lower" : true,
                "include_upper" : false
              }
            }
          } ]
        }
      }
    },
    "gender" : {
      "terms" : {
        "field" : "gender",
        "size" : 100
      },
      "facet_filter" : {
        "bool" : {
          "must" : [ {
            "term" : {
              "ni.language" : "en"
            }
          }, {
            "term" : {
              "dataview" : "7777"
            }
          }, {
            "range" : {
              "ni.authored_date" : {
                "from" : "2015-02-01T00:00:00",
                "to" : "2015-02-17T00:00:00",
                "include_lower" : true,
                "include_upper" : false
              }
            }
          } ]
        }
      }
    }
  }
} 
2015-03-30 14:57:00,067 INFO  [][89f0ee6696] com.networkedinsights.rest.search.elasticsearch.SearchExecution$QueryLogger - Query for cluster esdev_decahose on indices [[media_2015_05, media_2015_07, media_2015_06, media_2015_08]]:{
  "size" : 0,
  "query" : {
    "query_string" : {
      "query" : "smartwatch",
      "default_field" : "all"
    }
  },
  "filter" : {
    "bool" : {
      "must" : [ {
        "term" : {
          "ni.language" : "en"
        }
      }, {
        "term" : {
          "dataview" : "7777"
        }
      }, {
        "range" : {
          "ni.authored_date" : {
            "from" : "2015-02-01T00:00:00",
            "to" : "2015-02-17T00:00:00",
            "include_lower" : true,
            "include_upper" : false
          }
        }
      } ]
    }
  },
  "facets" : {
    "posts_by_date" : {
      "date_histogram" : {
        "field" : "authored_date",
        "interval" : "day"
      },
      "facet_filter" : {
        "bool" : {
          "must" : [ {
            "term" : {
              "ni.language" : "en"
            }
          }, {
            "term" : {
              "dataview" : "7777"
            }
          }, {
            "range" : {
              "ni.authored_date" : {
                "from" : "2015-02-01T00:00:00",
                "to" : "2015-02-17T00:00:00",
                "include_lower" : true,
                "include_upper" : false
              }
            }
          } ]
        }
      }
    },
    "gender" : {
      "terms" : {
        "field" : "gender",
        "size" : 100
      },
      "facet_filter" : {
        "bool" : {
          "must" : [ {
            "term" : {
              "ni.language" : "en"
            }
          }, {
            "term" : {
              "dataview" : "7777"
            }
          }, {
            "range" : {
              "ni.authored_date" : {
                "from" : "2015-02-01T00:00:00",
                "to" : "2015-02-17T00:00:00",
                "include_lower" : true,
                "include_upper" : false
              }
            }
          } ]
        }
      }
    }
  }
} 
2015-03-30 14:57:00,133 INFO  [][89f0ee6696] com.networkedinsights.rest.search.elasticsearch.SearchExecution$QueryLogger - Response for cluster esdev_decahose: {
  "took" : 31,
  "timed_out" : false,
  "_shards" : {
    "total" : 8,
    "successful" : 8,
    "failed" : 0
  },
  "hits" : {
    "total" : 9,
    "max_score" : 4.2796235,
    "hits" : [ ]
  },
  "facets" : {
    "posts_by_date" : {
      "_type" : "date_histogram",
      "entries" : [ {
        "time" : 1422835200000,
        "count" : 1
      }, {
        "time" : 1422921600000,
        "count" : 1
      }, {
        "time" : 1423008000000,
        "count" : 4
      }, {
        "time" : 1423094400000,
        "count" : 1
      }, {
        "time" : 1423180800000,
        "count" : 1
      }, {
        "time" : 1423440000000,
        "count" : 1
      } ]
    },
    "gender" : {
      "_type" : "terms",
      "missing" : 0,
      "total" : 9,
      "other" : 0,
      "terms" : [ {
        "term" : "unknown",
        "count" : 7
      }, {
        "term" : "male",
        "count" : 1
      }, {
        "term" : "female",
        "count" : 1
      } ]
    }
  }
} 
2015-03-30 14:57:00,135 INFO  [][89f0ee6696] com.networkedinsights.rest.search.elasticsearch.SearchExecution$QueryLogger - Response for cluster esdev_aud_vert: {
  "took" : 30,
  "timed_out" : false,
  "_shards" : {
    "total" : 4,
    "successful" : 4,
    "failed" : 0
  },
  "hits" : {
    "total" : 14,
    "max_score" : 2.034069,
    "hits" : [ ]
  },
  "facets" : {
    "posts_by_date" : {
      "_type" : "date_histogram",
      "entries" : [ {
        "time" : 1422748800000,
        "count" : 2
      }, {
        "time" : 1422921600000,
        "count" : 6
      }, {
        "time" : 1423008000000,
        "count" : 3
      }, {
        "time" : 1423094400000,
        "count" : 2
      }, {
        "time" : 1423353600000,
        "count" : 1
      } ]
    },
    "gender" : {
      "_type" : "terms",
      "missing" : 0,
      "total" : 14,
      "other" : 0,
      "terms" : [ {
        "term" : "male",
        "count" : 10
      }, {
        "term" : "female",
        "count" : 3
      }, {
        "term" : "unknown",
        "count" : 1
      } ]
    }
  }
}

**Comment by kilianc** [comment]
@rmchale thanks for explaining this to me, I appreciate it!

Now it seems like yours is an edge case where a `log line` in your case it's even a json object, translates in multiple lines because is formatted at the source.

Logs, by definitions are one line and delimited by `\n`, is there any way that you can make your logger emit a non formatted json object? rtail takes care of it already and you will be able to see 100 objects.

Btw, how do you use `tail -f` on a terminal with that amount of data in one shot ?

**Comment by rmchale** [comment]
For a terminal you change the scrollback options.  There are several instances where a single request in our systems logs more than 100 lines.  I am not particularly interested in reengineering logging to make a log viewer tool work.  I will just find a different tool.

**Comment by kilianc** [comment]
@rmchale well, was just trying to understand your particular case :) happy hunting!
