### ISSUE TITLE
pop-up triangle is the wrong color

### ISSUE THREAD

**Issue by timriot** [kilianc/rtail#52]
![r331mb_hk33j31vouhw-o9imwn7y8rehj4velmv_nis](https://cloud.githubusercontent.com/assets/1869621/8467663/305a2042-2016-11e5-9e90-54720bc0e5ca.png)

**Comment by kilianc** [comment]
thanks for reporting this, I must be color blind.

**Comment by kilianc** [comment]
@timriot wanna PR on this?

**Comment by timriot** [comment]
@kilianc I'm on it!
