### ISSUE TITLE
better social image

### ISSUE THREAD

**Issue by kilianc** [kilianc/rtail#53]
I designed one myself but it would be nice if one of the designers would give it a shot cc/ @lucaorio @SorelMihai @timriot 

https://developers.facebook.com/tools/debug/og/object?q=rtail.org

This is what it looks like now if you share it on FB

![](https://www.dropbox.com/s/u5zirnits4mshwc/Screenshot%202015-07-01%2020.04.43.png?dl=1)

**Comment by timriot** [comment]
PR https://github.com/kilianc/rtail/pull/54 cover this.
