### ISSUE TITLE
XSS Issue

### ISSUE THREAD

**Issue by MSylvia** [kilianc/rtail#62]
Any code in the `content` field get evaluated.

    [  
       "line",
       {  
          "timestamp":0000000000000,
          "streamid":"rtail.org",
          "host":"XXX.XXX.XXX.XXX",
          "port":50049,
          "content":"<script>window.top.location.href=\"http://www.google.com\"</script>",
          "type":"string"
       }
    ]

This would redirect the user to `http://www.google.com`

**Comment by MSylvia** [comment]
Also see Issue #61.

**Comment by kilianc** [comment]
I think I fixed this in: https://github.com/kilianc/rtail/issues/58

**Comment by kilianc** [comment]
@MSylvia thanks for reporting this first of all, I created a stream called "XSS no more" that should prove the fix works but since you're here, two more eyes would not hurt.

**Comment by MSylvia** [comment]
Ah I see that now. At the time I wrote it the current version of rtail.org had this issue. The fix might not have been deployed.

**Comment by kilianc** [comment]
@MSylvia yes, the demo is using a s3 bucket cached in ram for many hours. But someone has been faster than me tonight. I had to restart the demo and everything is working now. Along with other fixes and features like ellipsis for long names in the sidebar and resizable sidebar!

Shall we close this?

**Comment by MSylvia** [comment]
Yes. Seems to be resolved. :)
