### ISSUE TITLE
Layout different in firefox

### ISSUE THREAD

**Issue by assertnotnull** [kilianc/rtail#63]
Two scrollbars are displayed in firefox (v38) when the output is longer than the screen height and the resume button doesn't appear.

**Comment by kilianc** [comment]
only chrome is supported so far since the whole app uses flex. but I will look into it if it's an easy fix.

**Comment by assertnotnull** [comment]
flex is supported also in firefox

**Comment by kilianc** [comment]
@assertnotnull thanks for contributing and reporting ! I know :)

What I meant is that I have been using chrome only functionalities and I didn't test on other browsers, I will give my best shot as soon as I have time!

For example il looks fine on safari. Do you have a screenshot by any chance?

p.s. I closed this by mistake

**Comment by assertnotnull** [comment]
Sure here it is

![rtail](https://cloud.githubusercontent.com/assets/821567/8575738/9f41f4d0-256b-11e5-8e55-4ddb42c53f54.png)

**Comment by kilianc** [comment]
@assertnotnull I suspect this may be an issue with flexbox indeed, I will look into it. Stand by!

**Comment by kilianc** [comment]
@assertnotnull it appears to be a bug in firefox implementation ref: http://stackoverflow.com/questions/28636832/firefox-overflow-y-not-working-with-nested-flexbox

I think I may be able to force the height of the view to `100vh` and should not affect ~webkit.

**Comment by kilianc** [comment]
@assertnotnull give it a try with `--web-version unstable`

**Comment by kilianc** [comment]
btw, it turns out it a bug in chrome / webkit and firefox is the only one doing it right O_o

**Comment by assertnotnull** [comment]
Yes I've read that too lol.
