### ISSUE TITLE
Support grep color format

### ISSUE THREAD

**Issue by baptistemarchand** [kilianc/rtail#64]
Hi!

I'm having fun playing with rtail but I want to use it to monitor scripts that use grep to colorize their output and it doesn't seem to work well with rtail.
To reproduce, the following command should display 'lol' in red in the terminal but not in the rtail UI.
```
$ echo lol | grep --color=always lol | rtail --id test_grep
```
This is the format that grep uses:
```
$ echo lol | grep --color=always lol | cat -e
^[[01;31m^[[Klol^[[m^[[K$
```
I'm not sure if this is more of an ansi_up issue, or if there are some GREP_COLORS options I could set to fix it.

Thank you for your help and for building something cool!

**Comment by kilianc** [comment]
@baptistemarchand thanks for contributing.

ANSI parsing apparently is very hard. I spent quite some time looking for the "right" lib without luck. As you can see the color is parsed ~correctly, it may be a problem with `[K`. I will google it up but it's `ansi_up` issue. I am open to suggestions on alternative libs.

![8rdw6zhuc19ae4ydvwpcragx65kzg4q-8ierchasaxy](https://cloud.githubusercontent.com/assets/385716/8577524/21ac33b2-255e-11e5-9e79-b12916bd52f0.png)

**Comment by kilianc** [comment]
try this:
```
echo -e "\e[01;31mlol\e[m aaa" | rtail --name test_grep
```

the problem appears to be grep adding a clearline escape.

ref: http://unix.stackexchange.com/questions/45190/grep-color-adds-ansi-code-esck-this-can-change-displayed-text

**Comment by kilianc** [comment]
```
GREP_COLORS=ne echo lol aaa | grep --color=always lol | rtail --id test_grep
```

did we do it? :dancer:

**Comment by baptistemarchand** [comment]
Thanks for your quick answer!
I tried the GREP_COLORS solution yesterday and couldn't get it to work. After some investigation today it appears that BSD grep (the version used on mac) doesn't support the GREP_COLORS variable. I tried it on Linux and it works fine with GNU grep.
This is getting really outside the scope of rtail so you can probably close this issue. I'll let you know if I find an elegant workaround for OSX!
It might be useful to document the GREP_COLORS=ne thing somewhere, like in the README or some FAQ.
Thanks!

**Comment by kilianc** [comment]
@baptistemarchand I am on mac and the command I pasted here worked!

```
grep --version
grep (BSD grep) 2.5.1-FreeBSD
```

Double check if your doing something wrong and thanks for contributing.
