### ISSUE TITLE
Not getting all streamed info

### ISSUE THREAD

**Issue by kaihendry** [kilianc/rtail#66]
I am streaming an IRC session with [ii](http://tools.suckless.org/ii/) to my rtail server like so:

    sg:~/irc/irc.freenode.net/#hackerspacesg$ tail -F out | rtail --id hsg --host sg.dabase.com
    2015-07-09 15:33 -!- iilogbot(~iilogbot@sg.dabase.com) has joined #hackerspacesg
    2015-07-09 15:34 <hendry> another test
    2015-07-09 15:34 <hendry> http://sg.dabase.com:8888/#hsg
    2015-07-09 15:34 <WantonMee> [ rTail : loading ... ] - sg.dabase.com:8888

However it looks like this:

<img src=http://s.natalian.org/2015-07-09/1436428225_1918x1058.png>

It's missing the nick info `<hendry>` and duplicating the timestamp. Am I not using the right option?

**Comment by kilianc** [comment]
@kaihendry you are using the right options but your are running `0.1.1` which has those problems. you can manually install the develop branch and use it or just do

`rtail-server --web-version unstable` to fix the `<hendry>`, double timestamp is something I am working on. I will add the option to hide the left column in `v0.2.0`

**Comment by kaihendry** [comment]
Ah, thanks, it works as expected in unstable. http://s.natalian.org/2015-07-09/1436429117_1150x1058.png

**Comment by kilianc** [comment]
@kaihendry may I ask you more info about your use case? I am interested in knowing how people use this :)

and btw, thanks for contributing!

**Comment by kaihendry** [comment]
Use case is to show an IRC back channel on a big screen at http://hackerspace.sg/

**Comment by kilianc** [comment]
That's really cool! Thanks again.
