### ISSUE TITLE
Multiple white spaces displayed as single space.

### ISSUE THREAD

**Issue by vittee** [kilianc/rtail#68]
Specifying `white-space:pre` property to `.stream-line-content` solve this problem.

**Comment by kilianc** [comment]
Thanks this has been bother me for a long time @vittee !!! Do you want to sign this with a PR or do you want me to do it? I will be happy to add you to the contrib list!

**Comment by kilianc** [comment]
oh and I almost forgot:

![](http://i.giphy.com/JVdF14CQQH7gs.gif)

**Comment by vittee** [comment]
Thanks :)

I'm not familiar with Vincent Driessen branching model, and this is just a minor fix.
So I opened this issue and let the team do it instead.
