### ISSUE TITLE
Add date format in the settings menu

### ISSUE THREAD

**Issue by baptistemarchand** [kilianc/rtail#72]
Hi,

This is an idea for a feature.
It would be great if we could chose the date/time format in the settings menu.
I'm from France and the current format "07/13/15 02:32:41" is not really intuitive.
I would like to be able to select something like "13/07/15 14:32:41".

Thanks!

**Comment by kilianc** [comment]
@baptistemarchand yes this is a good idea and something I didn't think of at all. I need some UI for this so I will not be able to quickly patch it, but I can let webapp read the format from the settings and we can set it from chrome console while we wait for a bigger release.

Thanks for contributing @baptistemarchand !

**Comment by baptistemarchand** [comment]
Sounds good thanks!

**Comment by kilianc** [comment]
@baptistemarchand you can now open the console and `localforage.setItem('timestampFormat', 'MM/DD/YY')`, it will be available on unstable channel after deploy.

I use moment to format the date, you can see all the options here: http://momentjs.com/docs/#/displaying/

**Comment by baptistemarchand** [comment]
Thank you! :+1:
