### ISSUE TITLE
Web app fails to reconnect after internet outage

### ISSUE THREAD

**Issue by kaihendry** [kilianc/rtail#76]
I noticed that if the socket gets broken, the browser based applicaton doesn't seem to reconnect. Am I missing something?

**Comment by kilianc** [comment]
investigating

**Comment by kilianc** [comment]
@kaihendry if you are still running `--web-version unstable` you should get this in the next 6h with a hard browser reload. Let me know if it works for you. I am planning on releasing tomorrow.

**Comment by kaihendry** [comment]
Hmm, I just restarted `sudo rtail-server --web-version unstable --wh 172.31.10.190 --uh 172.31.10.190` and now it doesn't seem to work at all...

http://sg.dabase.com:8888/#/streams/hsg

**Comment by kilianc** [comment]
@kaihendry prob cache? The link you posted works for me

**Comment by kaihendry** [comment]
Oh so it does. Apologies for the noise. Thank you!

**Comment by kilianc** [comment]
@kaihendry don't apologize man, you have been super useful!!!!!!!! Here's a thank you gif for ya:

![](http://i.giphy.com/JVdF14CQQH7gs.gif)
