### ISSUE TITLE
Incomplete log

### ISSUE THREAD

**Issue by kaihendry** [kilianc/rtail#80]
![missing-whole-log](https://cloud.githubusercontent.com/assets/765871/8760577/bb8390ce-2d57-11e5-96bb-be4586b7722d.png)

Not entirely sure how to test which version I am running: http://sg.dabase.com:8888/#/streams/hsg

The last line where I say "tes" is what I expected to see on the browser!

**Comment by kilianc** [comment]
I see `tes`, it's just up at the top. I think you have inverted order in settings

**Comment by kilianc** [comment]
btw, version si `rtail --version` or `rtail-server --version` and in the `( i )` icon in the webapp :smile:

**Comment by kaihendry** [comment]
Oh, how do I not have it NOT invert please, without manually going into the gear icon upon http://sg.dabase.com:8888/#/streams/hsg ? Since we are just pointing a Webconverger instance to the page we want rendered by URL. Thanks!

**Comment by kilianc** [comment]
It doesn't default to that behavior, anyway, this is not this right place for this conversation, do you mind hopping in gitter?
