### ISSUE TITLE
Optional or variable client-side display buffer

### ISSUE THREAD

**Issue by Mmdixon** [kilianc/rtail#93]
Display seems to limit to 100 lines. Sometimes a message coming in (like a stacktrace) is more than 100 lines and would be nice to see the whole thing.

**Comment by kilianc** [comment]
Hi and thanks for contributing!

See issue https://github.com/kilianc/rtail/issues/42 - in future releases we will handle situations like these but by the time being 100 seems an acceptable number. I apologize for the issue in your specific use case!
