### ISSUE TITLE
Syntax highlighting / colorize support

### ISSUE THREAD

**Issue by jdrews** [kilianc/rtail#96]
Being able to colorize/ syntax highlight logs would be useful. 

Use case I envision is highlighting lines in red when ERROR shows up, and so on and so forth for other log levels.

**Comment by kilianc** [comment]
Syntax highlighting it's supported for JSON and ANSI colors work already. What exactly do you need?

**Comment by kilianc** [comment]
@jdrews thanks for contributing feel free to reopen this in case I didn't answer your question!

**Comment by jdrews** [comment]
Ah I didn't realize ANSI Colors were accepted. That might work. I will investigate. 

Here's the scenario: I have a ton of log4j/slf4j/logback java logs on (unfortunately) Windows systems. I'd like to view them remotely without having to Remote Desktop to these servers. And on top of that I'd like the logs to be colored based on severity levels (e.g. if there is WARN in line, mark line yellow, ERROR is red, INFO is green, etc). 

An example of these logs (but on one of the few Linux boxes) where I piped the output of the `tail -f` into a sed to colorize with ANSI colors. 
![a2fb8a9c-7a74-11e5-8b25-70bd01f3f396](https://cloud.githubusercontent.com/assets/172766/10826428/2b0d9064-7e40-11e5-8cf2-9dc48bc3c82f.jpg)

You can leave this issue closed. Just wanted to explain what I was talking about. Maybe this use case will help your design in the future.

**Comment by kilianc** [comment]
yeah this helps. so basically you were looking to have rtail client to do the coloring instead of sed?

**Comment by kilianc** [comment]
That may be an idea for front end. regexp patterns to switch the css of the line in question...

**Comment by jdrews** [comment]
Yeah that was the idea. Regular expressions to change colors of lines would be great. 

If this is something that could be saved in a config file or something like that so we didn't have to enter it in all the time would be much appreciated as well.
